### ISSUE TITLE
安装graph-tool 

### ISSUE THREAD

**Issue by gongchuanyang** [ruijie-wang-uzh/GNN2R#1]
安装graph-tool 总是会出现下面的问题：
ImportError: /opt/miniconda3/envs/gt/lib/python3.10/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /opt/miniconda3/envs/gt/lib/python3.10/site-packages/graph_tool/libgraph_tool_core.so)，不知道咋解决

**Comment by ruijie-wang-uzh** [comment]
Hi, I have not encountered an issue like this when installing graph_tool. 
Maybe create an empty conda environment and see if the installation works there?
Also, the graph_tool community has an issue report platform: https://git.skewed.de/count0/graph-tool/-/issues

**Comment by gongchuanyang** [comment]
thank you

**Comment by SJialong** [comment]
I also encountered the same problem, have you solved it?If so, how did you solve it? Thank you.

> thank you

**Comment by SJialong** [comment]
> I also encountered the same problem, have you solved it?If so, how did you solve it? Thank you.
> 
> > thank you

I've solved the problem)
